### ISSUE TITLE
App Devs can run OE SDK tools on Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#1027]
All tools that ship as part of the OE SDK need to build and run on Windows:

- [x] #837 Enable enclave signing on Windows (#956, #1027)
- [x] #838 Support oeedger8r on Windows (#895)
- [x] #1026 Enable oesgx on Windows (#1027)
