### ISSUE TITLE
App devs can build and load PE enclaves on Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#1040]
While the ability to run an ELF enclave on Windows provides basic cross-platform support, there is a strong preference for Windows developers not to have to leave the Windows ecosystem to develop enclave applications.

A fundamental step towards supporting that is to enable loading of Portable Executable (PE) format binaries as generated by Windows native tools (i.e. MSVC, link):

- [x] Support loading PE binaries as enclaves in OE loader (#811)
- [x] Support embedding SGX signatures in PE binaries (#811)
- [ ] #749 C99/11 standard is used for MSVC on Windows
- [ ] #1036 Support signing PE binaries in oesign
- [ ] #1035 Add separate build configuration for Windows to build and test PE enclaves
- [ ] #1038 Add support for 3rd party libraries in Windows PE enclaves
- [ ] #1115 Enable QSpecter flags when compiling with MSVC

This is closely tied to additional stories:
- #1037 App Devs have debugger support for PE enclaves on Windows

**Comment by ihaller** [comment]
A difficult and critical item missing from the list is porting the compiler runtime of MSVC.

**Comment by CodeMonkeyLeet** [comment]
Closing out issues related to Windows PE enclave support until we find a use case.
