### ISSUE TITLE
Repo users can rely on automated testing of core Open Enclave functionality

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#358]
Quality story to track that we complete our automated test coverage for extended Open Enclave core scenarios such as:

- [x] #23 Expand testing of enclave management scenarios
- [x] #24 Expand testing of thread binding behavior for enclaves
- [x] #25 Expand testing of memory management support in enclaves
