### ISSUE TITLE
Open Enclave users can build and test the repo without issues

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#396]
This story tracks that we resolve all issues just building and testing the OE repo in all the documented supported configurations. Issues that need to be resolved in this space include:

- [x] #325 libcxxrt test fails in release mode 
- [x] #348 Samples test fails in Simulation mode when built with OE_LIBSGX=1
- [x] #362 Install fails on intel SGX libs checksum verification
- [x] #365 Make error from command "cmake .." 
- [x] #466 Redirect Intel prereqs scripts to public endpoint
- [x] #573 libc test failures
- [x] #580 libcxx test failures with debug and optimized builds
- [x] #775 libcxx FULL tests fail to build after switch to Clang as default compiler
