### ISSUE TITLE
Maintainers can rely on a CI system to enforce build and test checks for PRs for Windows

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#51]
We need to onboard a Windows as a default CI configuration in Jenkins to catch build regressions, and specifically regressions in the ELF enclaves on Windows scenario:
- [x] #993 Enable Windows CI Builds
- [x] #1011 Test ELF enclaves on Windows in CI
- [x] #1002 Add a test-build-config batch file for Windows builds
- [x] Support Windows enclaves on DCAP in CI (resolved by PR #1417)

The previous investigation on this has been closed in favor of converging on the same CI Jenkins infrastructure as used for the Linux configurations:
> Need to set up a continuous integration pipelines for Windows, which requires extra investigation as the existing solution for Linux (#50) does not converge for Windows. 

> AppVeyor is one solution that other Azure teams have used and provide CI that is publicly visible to OSS contributors as well. 

> If we can get a single solution, this can be merged with the Linux one #50.
