### ISSUE TITLE
App Devs Using CMake can use exported CMake config from OE SDK

### ISSUE THREAD

**Issue by CodeMonkeyLeet** [Microsoft/openenclave#887]
This story tracks making the OE export of CMake targets a supported experience for devs who using CMake for their own application build and would like to just import the right targets and options for building against the OE SDK libs. This includes:
- [x] Verify the experimental config published in the SDK under lib/openenclave/cmake
- [x] Illustrate use with sample (#300)
- [x] Add CI build configuration to test this scenario (prevent regressions like #880)
- [x] Simplify targets for downstream CMake projects to consume (see #881)

**Comment by andschwa** [comment]
Closed via #1472.
